name: Atualizar submodulos

on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: 0 0 */2 * *

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Atualizando submodulos
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Subindo mudanças ao repositório
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          message: "update: plugins"
          push: true

