name: Trigger dependent repositories

on:
  - push

jobs:
  triggerWorkflows:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repos:
          - auto-champion-select
          - buy-champions
          - profile-utils
          - refund-last-purchase
  
    steps:    
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Check changes
        id: check_changes
        run: |
          git fetch
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          if echo "$CHANGED_FILES" | grep -q "controladoUtils.js"; then
          echo "::set-output name=modified::true"
          else
          echo "::set-output name=modified::false"
          fi

      - name: Trigger repositories
        if: steps.check_changes.outputs.modified == 'true'
        run: |
          for repo in "${{ matrix.repos }}"; do
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github.everest-preview+json" \
                 "https://api.github.com/repos/controlado/${repo}/dispatches" \
                 --data '{"event_type": "utils-updated"}'
          done
