name: Trigger dependent repositories

on:
  push:
    paths:
      - "controladoUtils.js"

jobs:
  triggerWorkflows:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repos:
          - random-champion
          - auto-champion-select
          - buy-champions
          - profile-utils
          - refund-last-purchase

    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files: controladoUtils.js

      - name: Trigger repositories
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for repo in "${{ matrix.repos }}"; do
            curl -X POST -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
                 -H "Accept: application/vnd.github.everest-preview+json" \
                 "https://api.github.com/repos/controlado/${repo}/dispatches" \
                 --data '{"event_type": "utils-updated"}'
          done
