name: Avisar repositórios dependentes

on:
  push:
    paths:
      - src/**

jobs:
  trigger-repositories:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repos:
          - profile-utils
          - refund-purchases
          - auto-champion-select
          - random-champion
          - buy-champions
          - shop-champion-select

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Avisando repositórios
        run: |
          for repo in "${{ matrix.repos }}"; do
            curl -X POST -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
                 -H "Accept: application/vnd.github.everest-preview+json" \
                 "https://api.github.com/repos/controlado/${repo}/dispatches" \
                 --data '{"event_type": "utils-updated"}'
          done
